version: '3.0' # specify docker-compose version

# Define the services/ containers to be run
services:
  api: # name of the second service
    build: ./
    ports:
      - "3000:3000" #specify ports mapping
    links:
      - database:27017 # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
